// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAegRk5EqPYpiXCke8IvlPJ9hBh3elZpSI',
    appId: '1:850656106213:web:fdacab66acd11ebb5b260c',
    messagingSenderId: '850656106213',
    projectId: 'max-v2-chat-app',
    authDomain: 'max-v2-chat-app.firebaseapp.com',
    storageBucket: 'max-v2-chat-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv6rExi-NmFc0npN06xIIuC18r7xgowzg',
    appId: '1:850656106213:android:47fc04046553cc085b260c',
    messagingSenderId: '850656106213',
    projectId: 'max-v2-chat-app',
    storageBucket: 'max-v2-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc6xhx0dY351Y7fnGSZHarMAvBe6UEOks',
    appId: '1:850656106213:ios:86211887ddc0267d5b260c',
    messagingSenderId: '850656106213',
    projectId: 'max-v2-chat-app',
    storageBucket: 'max-v2-chat-app.appspot.com',
    iosBundleId: 'com.example.chatAppV2',
  );
}
